In [10]:
#NUMPY
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))
print(np.array)
a.shape #gives result (3,) make 3 rows as 1 2 3 treats iterator


[1 2 3]
<class 'numpy.ndarray'>
<built-in function array>


(3,)

In [5]:
b=np.array([[1,2,3],[2,3,4]])

b.shape #gives rows and columns

(2, 3)

In [8]:
c=np.array([[2,2,2],[1,1,1]])
print(b+c)
print(b-c)
print(b*c) #not applicable as it dont follow matrix princple if order 2*3 then 2*3=3*2 to get correct result take transpose
print(b/c) 
print(b**c)
print(b//c)

[[3 4 5]
 [3 4 5]]
[[-1  0  1]
 [ 1  2  3]]
[[2 4 6]
 [2 3 4]]
[[0.5 1.  1.5]
 [2.  3.  4. ]]
[[1 4 9]
 [2 3 4]]
[[0 1 1]
 [2 3 4]]


In [13]:
d=np.transpose(c)
print(d)


[[2 1]
 [2 1]
 [2 1]]


In [15]:
print(np.dot(b,d))#use dot product to perform mulitplication of 2 d array


[[12  6]
 [18  9]]


In [20]:
arr=np.array([2,3,4,5])
arr.shape




dtype('int64')

In [21]:
arr.size #returns no of element

4

In [22]:
arr.ndim #return dimension

1

In [23]:
arr.dtype #return datatype


dtype('int64')

In [34]:
School=np.array(["box1","box2","box34"])
School.shape

(3,)

In [35]:
School.size

3

In [36]:
School.dtype

dtype('<U5')

In [30]:
School.ndim

1

In [42]:
marks=np.array([[55,22,31,56,100,30],[23,23,23,23,23,0]])
np.sum(marks)

np.int64(409)

In [43]:
print(np.sum(marks))


409


In [44]:
print(np.sum(marks,axis=0)) #give column sum


[ 78  45  54  79 123  30]


In [45]:
print(np.sum(marks,axis=1))

[294 115]


In [46]:
print(np.max(marks))

100


In [47]:
print(np.min(marks))

0


In [49]:
X=np.array([[1,2,3,4,5,6],[12,23,24,45,56,67]])

print(np.sum(X))

248


In [51]:
Y=np.array([[1,2,3,4,11,6],[12,23,24,45,56,67]])
print(sum(Y)) #gives sum matching element column wise

[13 25 27 49 67 73]


In [52]:
print(np.sum(Y,axis=0))

[13 25 27 49 67 73]


In [53]:
print(np.sum(Y,axis=1))

[ 27 227]
